# Lab 2 - Data Imputation
## JS02 - Data Understanding and Data Preprocessing

**Name:** Tiara Febrianie  
**Student ID:** 244107020097

In this lab, I fill in missing values in the Titanic dataset. The columns that need attention are `Age`, `Cabin`, and `Embarked`.

## Step 0 - Preparation

I use pandas to load the dataset and NumPy for numerical operations.

In [10]:
%pip install -q pandas numpy

import pandas as pd
import numpy as np

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Step 1 - Loading the Data

The Titanic CSV file is stored in the same folder as this notebook.

In [11]:
df = pd.read_csv("Titanic-Dataset.csv")

# Display the first five rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Step 2 - Data Inspection

Before filling the missing values, I check the data types and the number of empty values.

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [13]:
missing_before = df.isnull().sum()
missing_before[missing_before > 0]

Age         177
Cabin       687
Embarked      2
dtype: int64

## Step 3 - Data Imputation

I use a different method for each column:

- `Age` is numerical, so I use its mean value.
- `Cabin` has many missing values. I replace them with `DECK` to show that the cabin information is not available.
- `Embarked` has only a few missing values, so I use its most common value, or mode.

In [14]:
# Age - replace missing values with the mean
age_mean = np.mean(df["Age"].dropna())
df["Age"] = df["Age"].fillna(age_mean)

# Cabin - use a label for passengers without cabin information
df["Cabin"] = df["Cabin"].fillna("DECK")

# Embarked - replace missing values with the mode
embarked_mode = df["Embarked"].mode()[0]
df["Embarked"] = df["Embarked"].fillna(embarked_mode)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,DECK,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,DECK,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,DECK,S

## Step 4 - Result Validation

I check the data again to make sure that the selected columns no longer contain missing values.

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    str
 11  Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [16]:
missing_after = df[["Age", "Cabin", "Embarked"]].isnull().sum()
missing_after

Age         0
Cabin       0
Embarked    0
dtype: int64

In [17]:
print("Mean age used:", age_mean)
print("Embarked value used for missing rows:", embarked_mode)
print("Number of DECK values:", (df["Cabin"] == "DECK").sum())

Mean age used: 29.69911764705882
Embarked value used for missing rows: S
Number of DECK values: 687

## Optional - Save the Result

The completed dataset can be saved as a new CSV file. The original Titanic file is not overwritten.

In [18]:
df.to_csv("Titanic-Dataset-Fixed.csv", index=False)
print("Saved as Titanic-Dataset-Fixed.csv")

Saved as Titanic-Dataset-Fixed.csv

## Conclusion

The missing values in `Age`, `Cabin`, and `Embarked` have been filled using simple strategies. The cleaned data is ready for the next preprocessing step or for saving as a new CSV file.