# Lab 3 - Feature Selection, Encoding, and Standardization
## JS02 - Data Understanding and Data Preprocessing

**Name:** Tiara Febrianie  
**Student ID:** 244107020097

In this lab, I select useful features from the Titanic dataset, convert categorical values into numbers, and standardize the `Age` column.

## Overview

The features used in this example are `Survived`, `Pclass`, `Sex`, `Age`, and `Cabin`. The dataset was cleaned through the imputation process in Lab 2.

## Step 0 - Load the Libraries

I use pandas for the dataset. `LabelEncoder` changes text categories into numbers, while `StandardScaler` puts numerical values on a similar scale.

In [1]:
%pip install -q pandas scikit-learn

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

## Step 1 - Load the Data

The imputed Titanic dataset is stored in the same folder as this notebook.

In [2]:
dpath = "Titanic-Dataset-Fixed.csv"
df = pd.read_csv(dpath)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,DECK,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,DECK,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,DECK,S

## Step 2 - Slice the Data

I keep only the variables used in this exercise. `Survived` is the target variable, and the other columns are the selected features.

In [3]:
selected_columns = ["Survived", "Pclass", "Age", "Sex", "Cabin"]
df = df[selected_columns].copy()

df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male  DECK
1         1       1  38.0  female   C85
2         1       3  26.0  female  DECK
3         1       1  35.0  female  C123
4         0       3  35.0    male  DECK

## Step 3 - Encoding

`Sex` and `Cabin` contain text values. I use label encoding to convert each category into an integer.

In [4]:
sex_encoder = LabelEncoder()
cabin_encoder = LabelEncoder()

df["Sex"] = sex_encoder.fit_transform(df["Sex"])
df["Cabin"] = cabin_encoder.fit_transform(df["Cabin"])

df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    115
1         1       1  38.0    0     81
2         1       3  26.0    0    115
3         1       1  35.0    0     55
4         0       3  35.0    1    115

## Step 4 - Verify the Encoding Results

The categorical columns are now represented by integer values. The category mapping can be checked below.

In [5]:
print("Sex mapping:")
print(dict(zip(sex_encoder.classes_, sex_encoder.transform(sex_encoder.classes_))))

print("Number of cabin categories:", len(cabin_encoder.classes_))
df.info()

Sex mapping:
{'female': np.int64(0), 'male': np.int64(1)}
Number of cabin categories: 148
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Age       891 non-null    float64
 3   Sex       891 non-null    int64
 4   Cabin     891 non-null    int64
dtypes: float64(1), int64(4)
memory usage: 34.9 KB

## Step 5 - Standardization

I standardize `Age` with `StandardScaler`. This changes the values so that the column has a mean close to 0 and a standard deviation close to 1.

In [6]:
age_scaler = StandardScaler()
df["Age"] = age_scaler.fit_transform(df[["Age"]])

df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115

## Step 6 - Verify the Standardization Results

I check the mean and standard deviation to confirm the result.

In [7]:
print("Mean of standardized Age:", df["Age"].mean())
print("Standard deviation of standardized Age:", df["Age"].std())

df.head()

Mean of standardized Age: 2.2329064647904385e-16
Standard deviation of standardized Age: 1.0005616400330457

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115

## Conclusion

The selected variables are ready for machine learning. `Sex` and `Cabin` were encoded as numbers, and `Age` was standardized.